[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "flashcard_backend"
dynamic = ["version", "readme"]

[tool.setuptools.dynamic]
version = {attr = "flashcard_backend.VERSION"}